version: '3.4'

services:
  footballmatchmanager:
    image: ${DOCKER_REGISTRY-}footballmatchmanager
    build:
      context: .
      dockerfile: FootballMatchManager/Dockerfile

  client:
    image: client
    build:
      context: ./footballmatchmanagerreactclient
      dockerfile: Dockerfile
