version: '3.4'

services:
  footballmatchmanager:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "5000:80"
      - "443"

  client:
    ports:
      - "3000:3000"

  dbsql:
    container_name: dbsql
    image: mcr.microsoft.com/mssql/server:2019-latest
    environment:
    - MSSQL_SA_PASSWORD=test@123
    - ACCEPT_EULA=Y
    - MSSQL_PID=Express
    ports:
    - "1401:1433"
